
Program Strain
! The code AS_Calc_v1.10 calculates the strain field with data provided by AS_LBFG_v1.10 in half-torus, cone, truncated cone, pyramidal, core-shell quantum dots (QDs) heterostructures (QD=1,2,21,3,4). The QDs are of type AB/AC (three types of atoms A, B, C) for all QD shapes and, in addition, A/B (two types of atoms A, B) for core-shell.
! One needs the files: 111, 124, 201, temp280, temp240, temp260, and 601 or 6ab0 (e.g., 6010, 6120, ...) generated by code AS_LBFG_v1 (which also generates files of the atomic positions: 38,39,140,160,180).
!
    use DataType
    implicit none
integer:: q,i,j,m,ii,index
integer::m1, m2, m3, m4,counter,counterq,counterz
integer,allocatable:: n1(:), n2(:), n3(:), n4(:), atomi(:)
real*8,allocatable::  rp(:,:), rpr(:,:)
real*8:: radcut
real*8,allocatable:: rn1(:,:), rn2(:,:), rn3(:,:), rn4(:,:)
real*8,allocatable:: rn1r(:,:), rn2r(:,:), rn3r(:,:), rn4r(:,:)
real*8:: Idnt(3,3) 
real*8,allocatable:: MRini(:,:,:),MRfin(:,:,:),InvMRini(:,:,:),eps(:,:,:) 
real*8,allocatable:: DMini(:,:,:),AMR(:,:,:),InvDMini(:,:,:),FM(:,:,:),FMT(:,:,:) 
real*8,allocatable:: epsxx(:),epsyy(:),epszz(:),epsxy(:),epsxz(:),epsyz(:),epshyd(:),epshyd1(:)
real*8:: DetM,DetD
real*8,allocatable:: x(:),xr(:)
real*8::  ff, zcord
Real*8,allocatable:: radiuscut(:)
Real*8,allocatable::  Rcut(:)
Logical:: log
integer:: N13 
integer:: Rstrt  
real*8:: adf(5)
!integer: Casex
continue
!*******************************
!
    Open (15,file='StrainIni_v2.inp',status='old') !reading input parameters
    Read (15,*) nxp !nxp*a1 gives the radius for the cross-section
    Read (15,*) met ! strain tensor calculus method
    Read (15,*) radcut 
    Read(15,*) ff, index
    Read(15,*) msfit 
    Close (15)

allocate (radiuscut(1))
 Rewind(124)
    read(124,*) QD, WL, N1IN, N3OUT, N2IN, N4OUT, a1, a2, Geom_par1, Geom_par2, Geom_par3, adf,epscap,radiuscut,C11out,C12out,C11in,C12in,htj
    continue
    !
    call elastic_ct ! setting the elasticity parameters
! 
    
    If (QD==1)              Rt=Geom_par1; Rq=Geom_par2;
    If (QD==2 .or. QD==3)   Rc=Geom_par1; h=Geom_par2;
    If (QD==21)             Rc=Geom_par1; h=Geom_par2; htc=Geom_par3;
    If (QD==4)              RCO=Geom_par1; RCS=Geom_par2; 
!    
    if (QD==1) zcord=Rq !hemi-torus
    if (QD==2 .or. QD==3) zcord=h !cone or pyramid
    if (QD==21) zcord=htc !truncated cone
    if (QD==4) zcord=RCO ! core-shell
!
    allocate (Rcut(1))
    Rcut=radiuscut
    Nat1=N1in+N3out; Nat2=N2in; Nat3=N4out;  N13=Nat1;
continue
!
    Nt=Nat1+Nat2+Nat3
allocate(n1(Nt),n2(Nt),n3(Nt),n4(Nt)) !n1(w) is the index of 1st neighbor of atom #w, similarly for n2,n3,n4,
allocate(rp(Nt,3),rpr(Nt,3)) !x,y,z coords for each atom in unrelaxed config (rp) and relaxed config (rpr)
allocate(rn1(Nt,3),rn2(Nt,3),rn3(Nt,3),rn4(Nt,3)) !rn1 is for x,y,z coords of unrelaxed neighbor atom n1, etc.
allocate(rn1r(Nt,3),rn2r(Nt,3),rn3r(Nt,3),rn4r(Nt,3)) !rn1r is for x,y,z coords of relaxed neighbor atom n1, etc.
!
allocate(MRini(Nt,3,3),MRfin(Nt,3,3),InvMRini(Nt,3,3),eps(Nt,3,3))
allocate(DMini(Nt,3,3),AMR(Nt,3,3),InvDMini(Nt,3,3),FM(Nt,3,3),FMT(Nt,3,3))
allocate(x(3*Nt),xr(3*Nt))
!
rewind(201) !coords of each atom in the initial configuration
    do i=1,3*Nt,3
     read(201,*) x(i),x(i+1),x(i+2)
    end do
continue
!
rp=0!
 rewind(111) !index of each atom (rp) and its first 4 neighbors (rn) in the initial configuration
 do q=1,Nt 
    i=q
    ii=(i-1)*3+1
    read(111,*) i,n1(i),n2(i),n3(i),n4(i)
    m1=(n1(i)-1)*3+1; m2=(n2(i)-1)*3+1; m3=(n3(i)-1)*3+1; m4=(n4(i)-1)*3+1
    rp(i,1)=x(ii);rp(i,2)=x(ii+1);rp(i,3)=x(ii+2)    ! rp-position of the principal atom (Ga)
    rn1(i,1)=x(m1);rn1(i,2)=x(m1+1);rn1(i,3)=x(m1+2) ! rn1,rn2,rn3,rn4-the position of the 4 neighbors (Sb or As)
    rn2(i,1)=x(m2);rn2(i,2)=x(m2+1);rn2(i,3)=x(m2+2)
    rn3(i,1)=x(m3);rn3(i,2)=x(m3+1);rn3(i,3)=x(m3+2)
    rn4(i,1)=x(m4);rn4(i,2)=x(m4+1);rn4(i,3)=x(m4+2)
 end do
 continue
!
!------------------------------
!reading the relaxed atoms coords generated by code AS_LBFG_v1.10:
!rewind(6330)
rewind(601)
do i=1,3*Nt,3
!read(6330,*) xr(i),xr(i+1),xr(i+2)
read(601,*) xr(i),xr(i+1),xr(i+2)
end do
!------------------------------
!
rewind(111)
do q=1,Nt
    i=q
    ii=(i-1)*3+1
    !reading indexes i of principal atom (Ga) and n1,n2,n3,n4 of its first 4 neighbors in the initial configuration:
    read(111,*) i,n1(i),n2(i),n3(i),n4(i)
    m1=(n1(i)-1)*3+1; m2=(n2(i)-1)*3+1; m3=(n3(i)-1)*3+1; m4=(n4(i)-1)*3+1
    rpr(i,1)=xr(ii);rpr(i,2)=xr(ii+1);rpr(i,3)=xr(ii+2)    !rpr-position of the principal atom (Ga) after relaxation
    rn1r(i,1)=xr(m1);rn1r(i,2)=xr(m1+1);rn1r(i,3)=xr(m1+2) !rn1r,rn2r,rn3r,rn4r-position of the 4 neighbors (Sb or As) after relaxation
    rn2r(i,1)=xr(m2);rn2r(i,2)=xr(m2+1);rn2r(i,3)=xr(m2+2)
    rn3r(i,1)=xr(m3);rn3r(i,2)=xr(m3+1);rn3r(i,3)=xr(m3+2)
    rn4r(i,1)=xr(m4);rn4r(i,2)=xr(m4+1);rn4r(i,3)=xr(m4+2)
end do
!
!********************************************************
! Next, matrices are defined:
! Gullet method:
IF(met==2) then
do i=1, Nt !generates unrelaxed D_m matrix (Gullet, Modelling Simul. Mater. Sci. Eng. 16 (2008) 015001, eq.(22))
    DMini(i,1,1)=(rp(i,1)-rn1(i,1))*(rp(i,1)-rn1(i,1))+(rp(i,1)-rn2(i,1))*(rp(i,1)-rn2(i,1))+&
                 (rp(i,1)-rn3(i,1))*(rp(i,1)-rn3(i,1))+(rp(i,1)-rn4(i,1))*(rp(i,1)-rn4(i,1));
    DMini(i,1,2)=(rp(i,1)-rn1(i,1))*(rp(i,2)-rn1(i,2))+(rp(i,1)-rn2(i,1))*(rp(i,2)-rn2(i,2))+&
                 (rp(i,1)-rn3(i,1))*(rp(i,2)-rn3(i,2))+(rp(i,1)-rn4(i,1))*(rp(i,2)-rn4(i,2));
    DMini(i,1,3)=(rp(i,1)-rn1(i,1))*(rp(i,3)-rn1(i,3))+(rp(i,1)-rn2(i,1))*(rp(i,3)-rn2(i,3))+&
                 (rp(i,1)-rn3(i,1))*(rp(i,3)-rn3(i,3))+(rp(i,1)-rn4(i,1))*(rp(i,3)-rn4(i,3));
    DMini(i,2,1)=DMini(i,1,2);
    DMini(i,2,2)=(rp(i,2)-rn1(i,2))*(rp(i,2)-rn1(i,2))+(rp(i,2)-rn2(i,2))*(rp(i,2)-rn2(i,2))+&
                 (rp(i,2)-rn3(i,2))*(rp(i,2)-rn3(i,2))+(rp(i,2)-rn4(i,2))*(rp(i,2)-rn4(i,2));
    DMini(i,2,3)=(rp(i,2)-rn1(i,2))*(rp(i,3)-rn1(i,3))+(rp(i,2)-rn2(i,2))*(rp(i,3)-rn2(i,3))+&
                 (rp(i,2)-rn3(i,2))*(rp(i,3)-rn3(i,3))+(rp(i,2)-rn4(i,2))*(rp(i,3)-rn4(i,3));
    DMini(i,3,1)=DMini(i,1,3);
    DMini(i,3,2)=DMini(i,2,3);
    DMini(i,3,3)=(rp(i,3)-rn1(i,3))*(rp(i,3)-rn1(i,3))+(rp(i,3)-rn2(i,3))*(rp(i,3)-rn2(i,3))+&
                 (rp(i,3)-rn3(i,3))*(rp(i,3)-rn3(i,3))+(rp(i,3)-rn4(i,3))*(rp(i,3)-rn4(i,3));
end do
!
do i=1, Nt !generates unrelaxed D_m matrix (Gullet, Modelling Simul. Mater. Sci. Eng. 16 (2008) 015001, eq.)
    AMR(i,1,1)=(rpr(i,1)-rn1r(i,1))*(rp(i,1)-rn1(i,1))+(rpr(i,1)-rn2r(i,1))*(rp(i,1)-rn2(i,1))+&
                 (rpr(i,1)-rn3r(i,1))*(rp(i,1)-rn3(i,1))+(rpr(i,1)-rn4r(i,1))*(rp(i,1)-rn4(i,1));
    AMR(i,1,2)=(rpr(i,1)-rn1r(i,1))*(rp(i,2)-rn1(i,2))+(rpr(i,1)-rn2r(i,1))*(rp(i,2)-rn2(i,2))+&
                 (rpr(i,1)-rn3r(i,1))*(rp(i,2)-rn3(i,2))+(rpr(i,1)-rn4r(i,1))*(rp(i,2)-rn4(i,2));
    AMR(i,1,3)=(rpr(i,1)-rn1r(i,1))*(rp(i,3)-rn1(i,3))+(rpr(i,1)-rn2r(i,1))*(rp(i,3)-rn2(i,3))+&
                 (rpr(i,1)-rn3r(i,1))*(rp(i,3)-rn3(i,3))+(rpr(i,1)-rn4r(i,1))*(rp(i,3)-rn4(i,3));
    AMR(i,2,1)=(rpr(i,2)-rn1r(i,2))*(rp(i,1)-rn1(i,1))+(rpr(i,2)-rn2r(i,2))*(rp(i,1)-rn2(i,1))+&
                 (rpr(i,2)-rn3r(i,2))*(rp(i,1)-rn3(i,1))+(rpr(i,2)-rn4r(i,2))*(rp(i,1)-rn4(i,1));
    AMR(i,2,2)=(rpr(i,2)-rn1r(i,2))*(rp(i,2)-rn1(i,2))+(rpr(i,2)-rn2r(i,2))*(rp(i,2)-rn2(i,2))+&
                 (rpr(i,2)-rn3r(i,2))*(rp(i,2)-rn3(i,2))+(rpr(i,2)-rn4r(i,2))*(rp(i,2)-rn4(i,2));
    AMR(i,2,3)=(rpr(i,2)-rn1r(i,2))*(rp(i,3)-rn1(i,3))+(rpr(i,2)-rn2r(i,2))*(rp(i,3)-rn2(i,3))+&
                 (rpr(i,2)-rn3r(i,2))*(rp(i,3)-rn3(i,3))+(rpr(i,2)-rn4r(i,2))*(rp(i,3)-rn4(i,3));    
    AMR(i,3,1)=(rpr(i,3)-rn1r(i,3))*(rp(i,1)-rn1(i,1))+(rpr(i,3)-rn2r(i,3))*(rp(i,1)-rn2(i,1))+&
                 (rpr(i,3)-rn3r(i,3))*(rp(i,1)-rn3(i,1))+(rpr(i,3)-rn4r(i,3))*(rp(i,1)-rn4(i,1));
    AMR(i,3,2)=(rpr(i,3)-rn1r(i,3))*(rp(i,2)-rn1(i,2))+(rpr(i,3)-rn2r(i,3))*(rp(i,2)-rn2(i,2))+&
                 (rpr(i,3)-rn3r(i,3))*(rp(i,2)-rn3(i,2))+(rpr(i,3)-rn4r(i,3))*(rp(i,2)-rn4(i,2));
    AMR(i,3,3)=(rpr(i,3)-rn1r(i,3))*(rp(i,3)-rn1(i,3))+(rpr(i,3)-rn2r(i,3))*(rp(i,3)-rn2(i,3))+&
                 (rpr(i,3)-rn3r(i,3))*(rp(i,3)-rn3(i,3))+(rpr(i,3)-rn4r(i,3))*(rp(i,3)-rn4(i,3));
end do
END IF
!------------------------------------------
! Pryor method:        
IF(met==1) then
do i=1, Nt !generates unrelaxed R0 matrix (Pryor, J. Appl. Phys. 83, 2548 (1998))
    MRini(i,1,1)=rn1(i,1)-rn2(i,1); MRini(i,1,2)=rn2(i,1)-rn3(i,1); MRini(i,1,3)=rn3(i,1)-rn4(i,1);
    MRini(i,2,1)=rn1(i,2)-rn2(i,2); MRini(i,2,2)=rn2(i,2)-rn3(i,2); MRini(i,2,3)=rn3(i,2)-rn4(i,2);
    MRini(i,3,1)=rn1(i,3)-rn2(i,3); MRini(i,3,2)=rn2(i,3)-rn3(i,3); MRini(i,3,3)=rn3(i,3)-rn4(i,3);
end do
!   
counterq=0 !counts #atoms (met=1) for which eps is calculated
!
do i=1, Nt !generates relaxed R matrix (Pryor, J. Appl. Phys. 83, 2548 (1998))
    
    If((dabs(MRini(i,1,1)).lt.radcut).and.(dabs(MRini(i,1,2)).lt.radcut).and.(dabs(MRini(i,1,3)).lt.radcut)&
        .and.(dabs(MRini(i,2,1)).lt.radcut).and.(dabs(MRini(i,2,2)).lt.radcut).and.(dabs(MRini(i,2,3)).lt.radcut)&
        .and.(dabs(MRini(i,3,1)).lt.radcut).and.(dabs(MRini(i,3,2)).lt.radcut).and.(dabs(MRini(i,3,3)).lt.radcut)) then
  continue  
    MRfin(i,1,1)=rn1r(i,1)-rn2r(i,1); MRfin(i,1,2)=rn2r(i,1)-rn3r(i,1); MRfin(i,1,3)=rn3r(i,1)-rn4r(i,1);
    MRfin(i,2,1)=rn1r(i,2)-rn2r(i,2); MRfin(i,2,2)=rn2r(i,2)-rn3r(i,2); MRfin(i,2,3)=rn3r(i,2)-rn4r(i,2);
    MRfin(i,3,1)=rn1r(i,3)-rn2r(i,3); MRfin(i,3,2)=rn2r(i,3)-rn3r(i,3); MRfin(i,3,3)=rn3r(i,3)-rn4r(i,3);
    Else
     counterq=counterq+1
     Write(22,*)i !writes which (label) atoms are excluded from eps calculus
    End If        
end do
Print*, '# total of atoms is',  Nt
Print*, '# total of unrelaxed atoms for which |rn1(i,1)-rn2(i,1)|,.. etc. in MRini'
Print*, '  are larger than radcut',radcut,' Angstrom is',  counterq
!
END IF

do i=1,3 ! identity matrix
    do j=1,3
        If (i==j) then
        Idnt(i,j)=1d0
        else
        Idnt(i,j)=0d0
        end if
    end do
end do
!************************************************************
!
!Next, definition of the strain field follows. Two method are used: 1.Pryor, 2.Gullet.
allocate (epsxx(Nt-0),epsyy(Nt-0),epszz(Nt-0),epsxy(Nt-0),&
            epsxz(Nt-0),epsyz(Nt-0),epshyd(Nt-0),epshyd1(Nt-0))
epshyd(:)=epsxx(:)+epsyy(:)+epszz(:)

counter=0 !counts #atoms for wich eps is calculated.
!*********************************************
!
if(counterq.ne.0.and. met==1) then
allocate(atomi(counterq))    
rewind(22)
read(22,*) atomi
end if
!*********************************************
counterz=0 !counts #atoms (Ga) on z axis
!
CountAtoms: DO m=1,Nt
IF(counterq.ne.0 .and. met==1) then
do q=1,counterq !one avoids calculus of eps in the atoms for which |rn1(i,1)-rn2(i,1)|,.. etc in MRini are larger than radcut
    if(m==atomi(q)) go to 11    
end do
end if
 
continue
!------------------------------------------
! Pryor method:        
IF(met==1) then
call InvMatrix(MRini(m,:,:),InvMRini(m,:,:))
call Determ(MRini(m,:,:),DetM) 
if (dabs(DetM) .gt. 1d-12) then  
    eps(m,:,:)=MATMUL(MRfin(m,:,:),InvMRini(m,:,:))-Idnt ! eps-strain expression for atom m from pryor1998-VFF.pdf
end if
continue
END IF
!------------------------------------------
! Gullet method: 
IF(met==2) then
call InvMatrix(DMini(m,:,:),InvDMini(m,:,:))
call Determ(DMini(m,:,:),DetD) 
if (dabs(DetD) .gt. 1d-12) then     
FM(m,:,:)=MATMUL(AMR(m,:,:),InvDMini(m,:,:)) ! see  Gullet, Modelling Simul. Mater. Sci. Eng. 16 (2008) 015001, eq.(24)
Do i=1,3
    Do j=1,3
        FMT(m,i,j)=FM(m,j,i)
    end Do
end Do
eps(m,:,:)=(MATMUL(FMT(m,:,:),FM(m,:,:))-Idnt)/2
end if
continue
END IF
!***********************************************
!
If(QD==1) then
Call QDHTF(rp(m,1),rp(m,2),rp(m,3),log)
End If
continue

If(QD==2) then
Call QDConeF1(rp(m,1),rp(m,2),rp(m,3),log)
End If

If(QD==21) then
Call QDConeTruncF(rp(m,1),rp(m,2),rp(m,3),log)
End If

If(QD==3) then
Call QDPyramidF(rp(m,1),rp(m,2),rp(m,3),log)
End If
!
If(QD==4) then
 Call CSQDF(rp(m,1),rp(m,2),rp(m,3),log)
    if(rp(m,1)**2+rp(m,2)**2+rp(m,3)**2 .gt.RCO**2)then
          epsxx(m)=eps(m,1,1)+epscap;epsyy(m)=eps(m,2,2)+epscap;epszz(m)=eps(m,3,3)+epscap;
      else
        epsxx(m)=eps(m,1,1);epsyy(m)=eps(m,2,2);epszz(m)=eps(m,3,3);
     end if
    epshyd(m)=epsxx(m)+epsyy(m)+epszz(m) 
End If
!
!
IF(QD.ne.4) then ! strain for QD with WL
!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!==================================================
!
!Adapting eq.(9) from Pryor, J. Appl. Phys. 83, 2548 (1998):
!
If((log==.True.) .or. (rp(m,3).lt.-WL)) then
    epsxx(m)=eps(m,1,1);epsyy(m)=eps(m,2,2);epszz(m)=eps(m,3,3);
    epshyd(m)=epsxx(m)+epsyy(m)+epszz(m)
End If
!==================================================
!
If((log==.True.) .and. (rp(m,3).ge.-WL-0.1d0).and. (rp(m,3).le.0.1d0)) then
    epsxx(m)=eps(m,1,1)-0*epscap/1;epsyy(m)=eps(m,2,2)-0*epscap/1; epszz(m)=eps(m,3,3)+0*epscap/1;
    epshyd(m)=epsxx(m)+epsyy(m)+epszz(m)
End If
!==================================================
!
! For the capping domain (OUT of QD):
if((log==.False.) .and. (rp(m,3).ge.-WL)) then  
    !One substracts the initial artificial strain induced by the initial capping domain,
    !   which is built as having latt_ct=a2 (instead of realistic a1):
    !Next if forces the damping of epsxx, epsyy, epszz:
!----------
     if(rp(m,3).ge.adf(index)) then
     epsxx(m)=(eps(m,1,1)+epscap)*dexp(ff*(adf(index)-rp(m,3))/adf(index))
     epsyy(m)=(eps(m,2,2)+epscap)*dexp(ff*(adf(index)-rp(m,3))/adf(index))
     epszz(m)=(eps(m,3,3)+epscap)*dexp(ff*(adf(index)-rp(m,3))/adf(index))
     else ! next epsxx, epsyy, epszz are computed without the above forced damping, as obtained by minimization: 
        epsxx(m)=eps(m,1,1)+epscap; epsyy(m)=eps(m,2,2)+epscap; epszz(m)=eps(m,3,3)+epscap;
     end if     
!----------
    if (rp(m,3).ge.0d0) then ! for the capping domain
          write(771,*) rpr(m,1),rpr(m,2),rpr(m,3),epsxx(m),epsyy(m),epszz(m)        
    end if
!----------
    epshyd(m)=epsxx(m)+epsyy(m)+epszz(m)
    continue
end if
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! kind of interpolation:
if(dabs(epshyd(m)).gt.0.2 .and. m.gt.2 .and. m.lt.Nt-2 )then
    epshyd1(m)=(epshyd(m-2)+epshyd(m-1)+epshyd(m)+epshyd(m+1)+epshyd(m+2))/5
else
    epshyd1(m)=epshyd(m)
end if
!
END IF ! strain for QD with WL
!==================================================
continue
!==================================================
!
! CELL for the non-diagonal strain tensor
epsxy(m)=(eps(m,1,2)+eps(m,2,1))/2;
epsxz(m)=(eps(m,1,3)+eps(m,3,1))/2;
epsyz(m)=(eps(m,2,3)+eps(m,3,2))/2;
continue
!============================================================================
!
!COLLECTING STRAIN
!
write(6789,*) rpr(m,1),rpr(m,2),rpr(m,3),epsxx(m),epsyy(m),epszz(m),epshyd(m)
!======================================================================
! CELL for the semi-torus analysis (radius < nxp*a1)
!Strain field located in the uncommun atom of the heterostructure (e.g. Sb and As).
! Below rpr(m,1), rpr(m,1), rpr(m,1) are coords of atom 'm' after relaxation.
!
! For Sb (IN QD):
If(QD==1 .and. m.gt.Nat1 .and. m.le.(Nat1+Nat2) .and. dsqrt(rp(m,1)**2d0+rp(m,2)**2d0).le.nxp*a1) then
    write(8001,*)rpr(m,1),rpr(m,2),rpr(m,2), epsxx(m)
    write(8002,*)rp(m,1),rp(m,2),rp(m,2), epsxx(m)
    write(8011,*)rpr(m,1),rpr(m,2),rpr(m,2), epsyy(m)
    write(8012,*)rp(m,1),rp(m,2),rp(m,2), epsyy(m)
    write(8021,*)rpr(m,1),rpr(m,2),rpr(m,2), epszz(m)
    write(8022,*)rp(m,1),rp(m,2),rp(m,2), epszz(m)
        !write(8004,*)rpr(m,1),rpr(m,2),epsxy(m) !activate if desired
        !write(8005,*)rpr(m,1),rpr(m,2),epsxz(m) !activate if desired
        !write(8006,*)rpr(m,1),rpr(m,2),epsyz(m) !activate if desired
    write(8031,*)rpr(m,1),rpr(m,2),rpr(m,2), epshyd(m)
    write(8032,*)rp(m,1),rp(m,2),rp(m,2), epshyd(m)
End If
!
! For As (OUT QD):
If(QD==1 .and. m.gt.Nat2 .and. m.le.(Nat1+Nat2+Nat2) .and. dsqrt(rp(m,1)**2d0+rp(m,2)**2d0).le.nxp*a1) then
    write(8101,*)rpr(m,1),rpr(m,2),rpr(m,2), epsxx(m)
    write(8102,*)rp(m,1),rp(m,2),rp(m,2), epsxx(m)
    write(8111,*)rpr(m,1),rpr(m,2),rpr(m,2), epsyy(m)
    write(8112,*)rp(m,1),rp(m,2),rp(m,2), epsyy(m)
    write(8121,*)rpr(m,1),rpr(m,2),rpr(m,2), epszz(m)
    write(8122,*)rp(m,1),rp(m,2),rp(m,2), epszz(m)
        !write(8104,*)rpr(m,1),rpr(m,2),epsxy(m) !activate if desired
        !write(8105,*)rpr(m,1),rpr(m,2),epsxz(m) !activate if desired
        !write(8106,*)rpr(m,1),rpr(m,2),epsyz(m) !activate if desired
    write(8131,*)rpr(m,1),rpr(m,2),rpr(m,2), epshyd(m)
    write(8132,*)rp(m,1),rp(m,2),rp(m,2), epshyd(m)
End If
!
!======================================================================
!In a square(for pyramid) or disk(for cone, semi-torus, core-shell) of radius nxp*a1:
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!centered at z=0, z=zcord/2, z=zcord,  z=3*zcord/2, parallel to xy plane, and of thickness a1:

If(QD==4.and.(rpr(m,3).ge.-a1/4).and.(rpr(m,3).le.a1/4).and. (rpr(m,3)**2+rpr(m,2)**2+rpr(m,1)**2).le.RCS**2) then
    Casex=4
    !go to 10 !z=0 
    Else If((QD==1.or.QD==2).and.(rp(m, 3).ge.-a1/4).and.(rp(m, 3).le.a1/4).and. dsqrt(rp(m,1)**2d0+rp(m,2)**2d0).le.nxp*a1) then
    Casex=12
    Else If((QD==21).and.(rp(m, 3).ge.-a1/4).and.(rp(m, 3).le.a1/4).and. dsqrt(rp(m,1)**2d0+rp(m,2)**2d0).le.nxp*a1) then
    Casex=21
    !go to 10 !z=0 
    Else If (QD==3.and.(rp(m, 3).ge.-a1/4).and.(rp(m, 3).le.a1/4).and.(dabs(rp(m,1)).lt.nxp*a1).and.(dabs(rp(m,2)).lt.nxp*a1)) then
    Casex=3
    !    go to 10!z=0 
End If
!
If (Casex==4.or.Casex==12.or.Casex==21.or.Casex==3) then
        if (m.le.Nat1) then !For Ga atoms 
        write(1001,*)rpr(m,1),rpr(m,2),epsxx(m)
        write(1002,*)rpr(m,1),rpr(m,2),epsyy(m)
        write(1003,*)rpr(m,1),rpr(m,2),epszz(m)
        !write(1004,*)rpr(m,1),rpr(m,2),epsxy(m) !activate if desired
        !write(1005,*)rpr(m,1),rpr(m,2),epsxz(m) !activate if desired
        !write(1006,*)rpr(m,1),rpr(m,2),epsyz(m) !activate if desired
        write(1007,*)rpr(m,1),rpr(m,2),epshyd(m)
        end if
        if (m.le.Nt) then !For all atoms 
        write(2011,*)rpr(m,1),rpr(m,2),epsxx(m)
        write(2012,*)rpr(m,1),rpr(m,2),epsyy(m)
        write(2013,*)rpr(m,1),rpr(m,2),epszz(m)
        !write(2014,*)rpr(m,1),rpr(m,2),epsxy(m) !activate if desired
        !write(2015,*)rpr(m,1),rpr(m,2),epsxz(m) !activate if desired
        !write(2016,*)rpr(m,1),rpr(m,2),epsyz(m) !activate if desired
        write(2017,*)rpr(m,1),rpr(m,2),epshyd(m)
        end if
End If
Casex=0
!------------------------
!
If(QD==4.and.(rpr(m, 3).ge.zcord/2-a1/4).and.(rpr(m, 3).le.zcord/2+a1/4).and. (rpr(m,3)**2+rpr(m,2)**2+rpr(m,1)**2).le.RCS**2)then 
        Casex=4 !z=zcord/2
Else If((QD==1.or.QD==2).and.(rp(m, 3).ge.zcord/2-a1/4).and.(rp(m, 3).le.zcord/2+a1/4).and. dsqrt(rp(m,1)**2d0+rp(m,2)**2d0).le.nxp*a1) then
        Casex=12!z=zcord/2
Else If((QD==21).and.(rp(m, 3).ge.zcord/2-a1/4).and.(rp(m, 3).le.zcord/2+a1/4).and. dsqrt(rp(m,1)**2d0+rp(m,2)**2d0).le.nxp*a1) then
        Casex=21!z=zcord/2
Else If(QD==3.and.(rpr(m, 3).ge.zcord/2-a1/4).and.(rpr(m, 3).le.zcord/2+a1/4).and.(dabs(rp(m,1)).lt.nxp*a1).and.&
    (dabs(rp(m,2)).lt.nxp*a1)) then 
            Casex=3 !z=zcord/2
End If
!
    If (Casex==4.or.Casex==12.or.Casex==21.or.Casex==3) then
        if (m.le.Nat1) then !For Ga atoms 
        write(1101,*)rpr(m,1),rpr(m,2),epsxx(m)
        write(1102,*)rpr(m,1),rpr(m,2),epsyy(m)
        write(1103,*)rpr(m,1),rpr(m,2),epszz(m)
        !write(1104,*)rpr(m,1),rpr(m,2),epsxy(m) !activate if desired
        !write(1105,*)rpr(m,1),rpr(m,2),epsxz(m) !activate if desired
        !write(1106,*)rpr(m,1),rpr(m,2),epsyz(m) !activate if desired
        write(1107,*)rpr(m,1),rpr(m,2),epshyd(m)
        end if
        if (m.le.Nt) then !For all atoms 
        write(2111,*)rpr(m,1),rpr(m,2),epsxx(m)
        write(2112,*)rpr(m,1),rpr(m,2),epsyy(m)
        write(2113,*)rpr(m,1),rpr(m,2),epszz(m)
        !write(2114,*)rpr(m,1),rpr(m,2),epsxy(m) !activate if desired
        !write(2115,*)rpr(m,1),rpr(m,2),epsxz(m) !activate if desired
        !write(2116,*)rpr(m,1),rpr(m,2),epsyz(m) !activate if desired
        write(2117,*)rpr(m,1),rpr(m,2),epshyd(m)
        end if
    End If
Casex=0
!-----------------------------------------
!
If (QD==4 .and. (rp(m, 3).ge.zcord-a1/2).and.(rp(m, 3).le.zcord+a1/2).and. (rpr(m,3)**2+rpr(m,2)**2+rpr(m,1)**2).le.RCS**2) then
    Casex=4 !z=zcord
Else If((QD==1.or.QD==2).and.(rp(m, 3).ge.zcord-1*a1/2).and.(rp(m, 3).le.zcord+1*a1/2).and. dsqrt(rp(m,1)**2d0+rp(m,2)**2d0).le.nxp*a1) then
    Casex=12 !z=zcord
Else If((QD==21).and.(rp(m, 3).ge.zcord-1*a1/4).and.(rp(m, 3).le.zcord+1*a1/4).and. dsqrt(rp(m,1)**2d0+rp(m,2)**2d0).le.nxp*a1) then
    Casex=21 !z=zcord
Else If((QD==3.and.(rpr(m, 3).ge.zcord-a1/4).and.(rpr(m, 3).le.zcord+a1/4)).and.(dabs(rp(m,1)).lt.nxp*a1).and.&
    (dabs(rp(m,2)).lt.nxp*a1)) then
    Casex=3  !z=zcord
End if
    
!
    If (Casex==4.or.Casex==12.or.Casex==21.or.Casex==3) then
    if (m.le.Nat1) then !For Ga atoms
    write(1201,*)rpr(m,1),rpr(m,2),epsxx(m)
    write(1202,*)rpr(m,1),rpr(m,2),epsyy(m)
    write(1203,*)rpr(m,1),rpr(m,2),epszz(m)
       !write(1204,*)rpr(m,1),rpr(m,2),epsxy(m) !activate if desired
       !write(1205,*)rpr(m,1),rpr(m,2),epsxz(m) !activate if desired
      !write(1206,*)rpr(m,1),rpr(m,2),epsyz(m) !activate if desired
    write(1207,*)rpr(m,1),rpr(m,2),epshyd(m)
        end if
        if (m.le.Nt) then !For all atoms 
        write(2211,*)rpr(m,1),rpr(m,2),epsxx(m)
        write(2212,*)rpr(m,1),rpr(m,2),epsyy(m)
        write(2213,*)rpr(m,1),rpr(m,2),epszz(m)
        !write(2214,*)rpr(m,1),rpr(m,2),epsxy(m) !activate if desired
        !write(2215,*)rpr(m,1),rpr(m,2),epsxz(m) !activate if desired
        !write(2216,*)rpr(m,1),rpr(m,2),epsyz(m) !activate if desired
        write(2217,*)rpr(m,1),rpr(m,2),epshyd(m)
        end if
End If
Casex=0
!--------------------------------
!
If(QD==4.and.(rpr(m, 3).ge.zcord*1.5-a1/4).and.(rpr(m, 3).le.zcord*1.5+a1/4).and. (rpr(m,3)**2+rpr(m,2)**2+rpr(m,1)**2).le.RCS**2) then
    Casex=4 !z=3*zcord/2
Else If((QD==1.or.QD==2).and.(rp(m, 3).ge.zcord*1.5-a1/4).and.(rp(m, 3).le.zcord*1.5+a1/4).and. dsqrt(rp(m,1)**2d0+rp(m,2)**2d0).le.nxp*a1) then
    Casex=12  !z=3*zcord/2
Else If((QD==21).and.(rp(m, 3).ge.zcord*1.5-a1/4).and.(rp(m, 3).le.zcord*1.5+a1/4).and. dsqrt(rp(m,1)**2d0+rp(m,2)**2d0).le.nxp*a1) then
    Casex=21  !z=3*zcord/2
Else If((QD==3.and.rp(m, 3).ge.zcord*1.5-a1/4).and.(rp(m, 3).le.zcord*1.5+a1/4).and.(dabs(rp(m,1)).lt.nxp*a1).and.&
    (dabs(rp(m,2)).lt.nxp*a1)) then
    Casex=3  !z=3*zcord/2
    End If
    
!
    If (Casex==4.or.Casex==12.or.Casex==21.or.Casex==3) then
        if (m.le.Nat1) then !For Ga atoms
        write(1301,*)rpr(m,1),rpr(m,2),epsxx(m)
        write(1302,*)rpr(m,1),rpr(m,2),epsyy(m)
        write(1303,*)rpr(m,1),rpr(m,2),epszz(m)
        !write(1304,*)rpr(m,1),rpr(m,2),epsxy(m) !activate if desired
        !write(1305,*)rpr(m,1),rpr(m,2),epsxz(m) !activate if desired
        !write(1306,*)rpr(m,1),rpr(m,2),epsyz(m) !activate if desired
        write(1307,*)rpr(m,1),rpr(m,2),epshyd(m) !activate if desired
        end if
        if (m.le.Nt) then !For all atoms 
        write(2311,*)rpr(m,1),rpr(m,2),epsxx(m)
        write(2312,*)rpr(m,1),rpr(m,2),epsyy(m)
        write(2313,*)rpr(m,1),rpr(m,2),epszz(m)
        !write(2314,*)rpr(m,1),rpr(m,2),epsxy(m) !activate if desired
        !write(2315,*)rpr(m,1),rpr(m,2),epsxz(m) !activate if desired
        !write(2316,*)rpr(m,1),rpr(m,2),epsyz(m) !activate if desired
        write(2317,*)rpr(m,1),rpr(m,2),epshyd(m)
        end if
End If
Casex=0
!======================================================================
!
!    Strain along x axis: 
!If ((dabs(rp(m, 2)).lt.1d0).and.(dabs(rp(m, 3)).lt.1d0)) then !one takes some specific direction or plane; here x
!    if (m.le.Nat1) then !For Ga atoms 
!write(2201,*)rpr(m,1),epsxx(m)
!write(2202,*)rpr(m,1),epsyy(m)
!write(2203,*)rpr(m,1),epszz(m)
!write(2204,*)rpr(m,1),epshyd(m)
!    end if
!    if (m.le.Nt) then !For all atoms 
!write(2221,*)rpr(m,1),epsxx(m)
!write(2222,*)rpr(m,1),epsyy(m)
!write(2223,*)rpr(m,1),epszz(m)
!write(2224,*)rpr(m,1),epshyd(m)
!    end if
!end If
!======================================================================
!
!Strain along z axis:
If ((dabs(rp(m, 1)).lt.a1/10).and.(dabs(rp(m, 2)).lt.a1/10)) then
!"If ((dsqrt(rp(m, 1)**2+rp(m, 2)**2).lt.a1/1.5)) then
!   counterz=counterz+1
    if (m.le.Nat1) then !For Ga atoms 
        if(QD==3) then ! for pyramidal shape
        ! Next command using 'rp' instead the below, after 'else', using 'rpr' gives better match with Fig.[4] from Grundmann et al. Phys. Rev. B 52 (1995) 11969-11981 for InAs/GaAs pyramidal QD
write(3401,*)rp(m,3),epsxx(m); write(3402,*)rp(m,3),epsyy(m); write(3403,*)rp(m,3),epszz(m); write(3404,*)rp(m,3),epshyd(m)
        else
write(3401,*)rpr(m,3),epsxx(m); write(3402,*)rpr(m,3),epsyy(m); write(3403,*)rpr(m,3),epszz(m); write(3404,*)rpr(m,3),epshyd(m)
!write(3401,*)rp(m,3),epsxx(m); write(3402,*)rp(m,3),epsyy(m); write(3403,*)rp(m,3),epszz(m); write(3404,*)rp(m,3),epshyd(m)
        end if
    end if
end If
!
If ((dabs(rp(m, 1)).gt.a1/10).and.(dabs(rp(m, 1)).lt.a1/3) .and. (dabs(rp(m, 2)).gt.a1/10).and.(dabs(rp(m, 2)).lt.a1/3)) then
    if ((m .gt. Nat1) .and. (m .lt. Nt)) then !For all atoms
        if(QD==3) then ! for pyramidal shape
        ! Next command using 'rp' instead the below, after 'else', using 'rpr' gives better match with Fig.[4] from Grundmann et al. Phys. Rev. B 52 (1995) 11969-11981 for InAs/GaAs pyramidal QD
write(3411,*)rp(m,3),epsxx(m);  write(3412,*)rp(m,3),epsyy(m); write(3413,*)rp(m,3),epszz(m); write(3414,*)rp(m,3),epshyd(m)
        else
write(3411,*)rpr(m,3),epsxx(m);  write(3412,*)rpr(m,3),epsyy(m); write(3413,*)rpr(m,3),epszz(m); write(3414,*)rpr(m,3),epshyd(m)
        end if
    end if
end If
!======================================================================
!
!Strain along y axis: 
If ((dabs(rp(m, 1)).lt.a1/10).and.(dabs(rp(m, 3)).lt.a1/10)) then
    counterz=counterz+1
    if (m.le.Nat1) then !For Ga atoms 
!write(3401,*)rpr(m,2),epsxx(m); write(3402,*)rpr(m,2),epsyy(m); write(3403,*)rpr(m,2),epszz(m); write(3404,*)rpr(m,2),epshyd(m)
    end if
    if (m.le.Nt) then !For all atoms 
!write(3411,*)rpr(m,2),epsxx(m); write(3412,*)rpr(m,2),epsyy(m); write(3413,*)rpr(m,2),epszz(m); write(3414,*)rpr(m,2),epshyd(m)
    end if
end If
!======================================================================
!
!Strain along x axis: 
If ((dabs(rpr(m, 3)).lt.a1/10).and.(dabs(rpr(m, 2)).lt.a1/10)) then
!    counterz=counterz+1
    if (m.le.Nat1) then !For Ga atoms 
!write(3401,*)rpr(m,1),epsxx(m); write(3402,*)rpr(m,1),epsyy(m); write(3403,*)rpr(m,1),epszz(m); write(3404,*)rpr(m,1),epshyd(m)
    end if
    if (m.le.Nt) then !For all atoms 
!write(3411,*)rpr(m,1),epsxx(m); write(3412,*)rpr(m,1),epsyy(m); write(3413,*)rpr(m,1),epszz(m); write(3414,*)rpr(m,1),epshyd(m)
    end if
end If
!
    counter=counter+1 
!
11 continue
!======================================================================
END DO CountAtoms
!----------------------------------------------
!
Rstrt=1;
Call Misfit(Rcut,Rstrt,xr,N13)
!
if (counter.eq.0) then
   print*,'Strain field is not calculated in any point of the unrelaxed structure. Increase radcut in the input file.'
   print*,'If eps in xy plane is not calculated change z layer width'
    else    
   print*, 'radcut=',radcut,'Angström'
   if (met==1) then
       print*,'Strain field is calculated by Pryor method for the xy-plane, x, y, and z directions. See the name of files in manual.'
   end if
!
   if (met==2) then
       print*,'Strain field is calculated by Gullet method for the xy-plane, x, y, and z directions. See the name of files in manual.'
   end if
!
    end if
!
Print*,'There are',counterz, 'atoms on z axis.'
continue
end Program Strain
!***********************************************
!
    Subroutine InvMatrix(R,InvR)
implicit none
real*8:: A(3,3),R(3,3),InvR(3,3),InvR1(3,3)
real*8:: Det
!
    A(1,1)=R(2,2)*R(3,3)-R(2,3)*R(3,2)
    A(1,2)=-(R(2,1)*R(3,3)-R(2,3)*R(3,1))
    A(1,3)=R(2,1)*R(3,2)-R(2,2)*R(3,1)
    A(2,1)=-(R(1,2)*R(3,3)-R(3,2)*R(1,3)) 
    A(2,2)=R(1,1)*R(3,3)-R(1,3)*R(3,1)
    A(2,3)=-(R(1,1)*R(3,2)-R(1,2)*R(3,1))
    A(3,1)=R(1,2)*R(2,3)-R(2,2)*R(1,3)
    A(3,2)=-(R(1,1)*R(2,3)-R(2,1)*R(1,3))
    A(3,3)=R(1,1)*R(2,2)-R(1,2)*R(2,1)
    
    Det=R(1,1)*R(2,2)*R(3,3)+R(2,1)*R(3,2)*R(1,3)+&
        R(1,2)*R(2,3)*R(3,1)-R(3,1)*R(2,2)*R(1,3)-&
        R(1,1)*R(2,3)*R(3,2)-R(3,3)*R(1,2)*R(2,1)
!

InvR1=A/Det
continue
InvR(1,1)=InvR1(1,1);InvR(2,2)=InvR1(2,2);InvR(3,3)=InvR1(3,3);
InvR(1,2)=InvR1(2,1);InvR(2,1)=InvR1(1,2);
InvR(1,3)=InvR1(3,1);InvR(3,1)=InvR1(1,3);
InvR(2,3)=InvR1(3,2);InvR(3,2)=InvR1(2,3);
continue

end Subroutine InvMatrix
!***********************************************
!
    Subroutine Determ(mt,Det)
implicit none
real*8:: mt(3,3),Det
Det=mt(1,1)*mt(2,2)*mt(3,3)+mt(2,1)*mt(3,2)*mt(1,3)+&
        mt(1,2)*mt(2,3)*mt(3,1)-mt(3,1)*mt(2,2)*mt(1,3)-&
        mt(1,1)*mt(2,3)*mt(3,2)-mt(3,3)*mt(1,2)*mt(2,1)
    
    end Subroutine Determ    
!***********************************************
!  
    Subroutine QDHTF(x,y,z,log)
    !QDHTF-quantum dot semi-torus function
    !Generates semi-torus function in Cartesian coords
    !Rq-torus radius; Rt1-internal radius of the h-torus; Rt2-outer radius of the h-torus
   use DataType
    Real*8:: Rt1, Rt2, x, y, z, rho !, WL
    Logical:: log ! , log1, log2
    Rt1=Rt-Rq
    Rt2=Rt+Rq  
	rho=dsqrt(x**2+y**2)
        
    log=((rho.ge.Rt1).and.(rho.le.Rt2).and.((rho-Rt)**2+z**2.le.Rq**2).and.(z.ge.0d0))! log=true for (x,y,z) inside+boundary h-torus    
    
    End Subroutine QDHTF
!********************************************* 
!
    Subroutine QDConeF1(x,y,z,log)
    !QDHTF-quantum dot Cone  function. Generates Cone function in Cartesian
    !Rc-con radius; h-cone height
use DataType
Real*8::  x, y, z, rho
Logical:: log
    rho=dsqrt(x**2+y**2)   
    log=(rho.le.(h-z)*Rc/h) .and.(z.le.h).and.(z.ge.0d0)! log=true for (x,y,z) inside the Cone and its surface
!continue
    End Subroutine QDConeF1    
!*********************************************  
!    
Subroutine QDConeTruncF(x,y,z,log)
    !Generates truncated cone function in Cartesian
    !Rc-cone radius; h-cone height; ht-height of 
use DataType
integer, parameter :: dp = kind(1.0d0)
Real(dp)::  x, y, z, rho
Logical:: log
    rho=dsqrt(x**2+y**2)   
    log=(rho.le.(h-z)*Rc/h) .and.(z.le.htc).and.(z.gt.0d0)! log=true for (x,y,z) inside the Cone and its surface
    if (htc.ge.h) then
    write (6,61)
61  format ('The height of truncated cone htc can not be larger than its height. Change htc in VFF_v1.10.inp.')
    STOP
    end if
!continue
    End Subroutine QDConeTruncF
!********************************************* 
!    
Subroutine QDPyramidF(x,y,z,log)
    !Generates rectangular pyramid function in Cartesian
    !b=Rc-half of the baze; h-pyramid height
use DataType
integer, parameter :: dp = kind(1.0d0)
Real(dp)::  x, y, z, fpyr
Logical:: log
    fpyr=(h-z)*Rc/h   
    log=x.ge.-fpyr.and.x.le.fpyr.and.y.ge.-fpyr.and.y.le.fpyr.and.z.ge.0d0.and.z.le.h ! log=true for (x,y,z) inside the pyramid and its surface
!continue
    End Subroutine QDPyramidF
!********************************************* 
!    
Subroutine CSQDF(x,y,z,log)
    !Generates core-shell QD
    !RCO-core radius; RCS-core+shell radius
use DataType
integer, parameter :: dp = kind(1.0d0)
Real(dp)::  x, y, z
Logical:: log
log=(x**2+y**2+z**2).le.RCO**2 !(x,y,z) inside the coreand its surface
!continue
End Subroutine CSQDF
!*********************************************   